# -*- coding: utf-8 -*-
"""Multi_dataframe_Agents.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EG9TGhr1h9BXZKWSwFB_6x3p9dy_iuXU
"""

!pip install langchain langchain_experimental
!pip install watermark
!pip install openai

import os
import warnings
warnings.filterwarnings('ignore')

from langchain_experimental.agents.agent_toolkits import create_pandas_dataframe_agent
from langchain_community.llms import OpenAI

import pandas as pd

os.environ["OPENAI_API_KEY"]= "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"
os.environ["OPENAI_API_BASE"] = "https://openrouter.ai/api/v1"

url= "https://raw.githubusercontent.com/adamerose/datasets/master/titanic.csv"
df= pd.read_csv(url)
print(df.shape)
df.head()

"""# Agents can interact with Single DataFrame"""

llm= OpenAI()

agent= create_pandas_dataframe_agent(llm, df, verbose=True, allow_dangerous_code=True)

agent.run("how many people have more than 23 age")

"""# Multi Dataframe examples"""

df.info()

df1= df.copy()

df['age']= df1['age'].fillna(df1["age"].mean())

agent= create_pandas_dataframe_agent(llm, [df, df1], verbose= True, allow_dangerous_code=True)

agent.run("How many rows in the age column are different")

df2= df1.copy()

df2["Age_multiplied"]= df1["age"]*2

df2.head()

agent.run("Are the number of columns same in all dataframes")

